fqbn = {
    "4D Systems gen4 IoD Range": ("esp8266:esp8266:gen4iod", "4D Systems gen4 IoD Range"),
    "Adafruit Circuit Playground": ("arduino:avr:circuitplay32u4cat", "Adafruit Circuit Playground"),
    "Adafruit Circuit Playground Express": ("arduino:samd:adafruit_circuitplayground_m0", "Adafruit Circuit Playground Express"),
    "Adafruit Feather HUZZAH ESP8266": ("esp8266:esp8266:huzzah", "Adafruit Feather HUZZAH ESP8266"),
    "Amperka WiFi Slot": ("esp8266:esp8266:wifi_slot", "Amperka WiFi Slot"),
    "Arduino": ("esp8266:esp8266:arduino-esp8266", "Arduino"),
    "Arduino BT": ("arduino:avr:bt", "Arduino BT"),
    "Arduino Duemilanove or Diecimila": ("arduino:avr:diecimila", "Arduino Duemilanove or Diecimila"),
    "Arduino Esplora": ("arduino:avr:esplora", "Arduino Esplora"),
    "Arduino Ethernet": ("arduino:avr:ethernet", "Arduino Ethernet"),
    "Arduino Fio": ("arduino:avr:fio", "Arduino Fio"),
    "Arduino Gemma": ("arduino:avr:gemma", "Arduino Gemma"),
    "Arduino Industrial 101": ("arduino:avr:chiwawa", "Arduino Industrial 101"),
    "Arduino Leonardo": ("arduino:avr:leonardo", "Arduino Leonardo"),
    "Arduino Leonardo ETH": ("arduino:avr:leonardoeth", "Arduino Leonardo ETH"),
    "Arduino M0": ("arduino:samd:mzero_bl", "Arduino M0"),
    "Arduino M0 Pro (Native USB Port)": ("arduino:samd:mzero_pro_bl", "Arduino M0 Pro (Native USB Port)"),
    "Arduino M0 Pro (Programming Port)": ("arduino:samd:mzero_pro_bl_dbg", "Arduino M0 Pro (Programming Port)"),
    "Arduino MKR FOX 1200": ("arduino:samd:mkrfox1200", "Arduino MKR FOX 1200"),
    "Arduino MKR GSM 1400": ("arduino:samd:mkrgsm1400", "Arduino MKR GSM 1400"),
    "Arduino MKR NB 1500": ("arduino:samd:mkrnb1500", "Arduino MKR NB 1500"),
    "Arduino MKR Vidor 4000": ("arduino:samd:mkrvidor4000", "Arduino MKR Vidor 4000"),
    "Arduino MKR WAN 1300": ("arduino:samd:mkrwan1300", "Arduino MKR WAN 1300"),
    "Arduino MKR WAN 1310": ("arduino:samd:mkrwan1310", "Arduino MKR WAN 1310"),
    "Arduino MKR WiFi 1010": ("arduino:samd:mkrwifi1010", "Arduino MKR WiFi 1010"),
    "Arduino MKR1000": ("arduino:samd:mkr1000", "Arduino MKR1000"),
    "Arduino MKRZERO": ("arduino:samd:mkrzero", "Arduino MKRZERO"),
    "Arduino Mega ADK": ("arduino:avr:megaADK", "Arduino Mega ADK"),
    "Arduino Mega or Mega 2560": ("arduino:avr:mega", "Arduino Mega or Mega 2560"),
    "Arduino Micro": ("arduino:avr:micro", "Arduino Micro"),
    "Arduino Mini": ("arduino:avr:mini", "Arduino Mini"),
    "Arduino NANO 33 IoT": ("arduino:samd:nano_33_iot", "Arduino NANO 33 IoT"),
    "Arduino NG or older": ("arduino:avr:atmegang", "Arduino NG or older"),
    "Arduino Nano": ("arduino:avr:nano", "Arduino Nano"),
    "Arduino Pro or Pro Mini": ("arduino:avr:pro", "Arduino Pro or Pro Mini"),
    "Arduino Robot Control": ("arduino:avr:robotControl", "Arduino Robot Control"),
    "Arduino Robot Motor": ("arduino:avr:robotMotor", "Arduino Robot Motor"),
    "Arduino Tian": ("arduino:samd:tian", "Arduino Tian"),
    "Arduino Uno": ("arduino:avr:uno", "Arduino Uno"),
    "Arduino Uno Mini": ("arduino:avr:unomini", "Arduino Uno Mini"),
    "Arduino Uno WiFi": ("arduino:avr:unowifi", "Arduino Uno WiFi"),
    "Arduino Yún": ("arduino:avr:yun", "Arduino Yún"),
    "Arduino Yún Mini": ("arduino:avr:yunmini", "Arduino Yún Mini"),
    "Arduino Zero (Native USB Port)": ("arduino:samd:arduino_zero_native", "Arduino Zero (Native USB Port)"),
    "Arduino Zero (Programming Port)": ("arduino:samd:arduino_zero_edbg", "Arduino Zero (Programming Port)"),
    "DOIT ESP-Mx DevKit (ESP8285)": ("esp8266:esp8266:espmxdevkit", "DOIT ESP-Mx DevKit (ESP8285)"),
    "Digistump Oak": ("esp8266:esp8266:oak", "Digistump Oak"),
    "ESPDuino (ESP-13 Module)": ("esp8266:esp8266:espduino", "ESPDuino (ESP-13 Module)"),
    "ESPectro Core": ("esp8266:esp8266:espectro", "ESPectro Core"),
    "ESPino (ESP-12 Module)": ("esp8266:esp8266:espino", "ESPino (ESP-12 Module)"),
    "ESPresso Lite 1.0": ("esp8266:esp8266:espresso_lite_v1", "ESPresso Lite 1.0"),
    "ESPresso Lite 2.0": ("esp8266:esp8266:espresso_lite_v2", "ESPresso Lite 2.0"),
    "Generic ESP8266 Module": ("esp8266:esp8266:generic", "Generic ESP8266 Module"),
    "Generic ESP8285 Module": ("esp8266:esp8266:esp8285", "Generic ESP8285 Module"),
    "ITEAD Sonoff": ("esp8266:esp8266:sonoff", "ITEAD Sonoff"),
    "Invent One": ("esp8266:esp8266:inventone", "Invent One"),
    "LOLIN(WEMOS) D1 R2 & mini": ("esp8266:esp8266:d1_mini", "LOLIN(WEMOS) D1 R2 & mini"),
    "LOLIN(WEMOS) D1 mini (clone)": ("esp8266:esp8266:d1_mini_clone", "LOLIN(WEMOS) D1 mini (clone)"),
    "LOLIN(WEMOS) D1 mini Lite": ("esp8266:esp8266:d1_mini_lite", "LOLIN(WEMOS) D1 mini Lite"),
    "LOLIN(WEMOS) D1 mini Pro": ("esp8266:esp8266:d1_mini_pro", "LOLIN(WEMOS) D1 mini Pro"),
    "LOLIN(WeMos) D1 R1": ("esp8266:esp8266:d1", "LOLIN(WeMos) D1 R1"),
    "Lifely Agrumino Lemon v4": ("esp8266:esp8266:agruminolemon", "Lifely Agrumino Lemon v4"),
    "LilyPad Arduino": ("arduino:avr:lilypad", "LilyPad Arduino"),
    "LilyPad Arduino USB": ("arduino:avr:LilyPadUSB", "LilyPad Arduino USB"),
    "Linino One": ("arduino:avr:one", "Linino One"),
    "NodeMCU 0.9 (ESP-12 Module)": ("esp8266:esp8266:nodemcu", "NodeMCU 0.9 (ESP-12 Module)"),
    "NodeMCU 1.0 (ESP-12E Module)": ("esp8266:esp8266:nodemcuv2", "NodeMCU 1.0 (ESP-12E Module)"),
    "Olimex MOD-WIFI-ESP8266(-DEV)": ("esp8266:esp8266:modwifi", "Olimex MOD-WIFI-ESP8266(-DEV)"),
    "Phoenix 1.0": ("esp8266:esp8266:phoenix_v1", "Phoenix 1.0"),
    "Phoenix 2.0": ("esp8266:esp8266:phoenix_v2", "Phoenix 2.0"),
    "Schirmilabs Eduino WiFi": ("esp8266:esp8266:eduinowifi", "Schirmilabs Eduino WiFi"),
    "Seeed Wio Link": ("esp8266:esp8266:wiolink", "Seeed Wio Link"),
    "SparkFun Blynk Board": ("esp8266:esp8266:blynk", "SparkFun Blynk Board"),
    "SparkFun ESP8266 Thing": ("esp8266:esp8266:thing", "SparkFun ESP8266 Thing"),
    "SparkFun ESP8266 Thing Dev": ("esp8266:esp8266:thingdev", "SparkFun ESP8266 Thing Dev"),
    "SweetPea ESP-210": ("esp8266:esp8266:esp210", "SweetPea ESP-210"),
    "ThaiEasyElec's ESPino": ("esp8266:esp8266:espinotee", "ThaiEasyElec's ESPino"),
    "WiFi Kit 8": ("esp8266:esp8266:wifi_kit_8", "WiFi Kit 8"),
    "WiFiduino": ("esp8266:esp8266:wifiduino", "WiFiduino"),
    "WifInfo": ("esp8266:esp8266:wifinfo", "WifInfo"),
    "XinaBox CW01": ("esp8266:esp8266:cw01", "XinaBox CW01"),
}