# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: init.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ninit.proto\"\x16\n\x05Input\x12\r\n\x05\x63heck\x18\x01 \x01(\x08\"-\n\x0b\x43redentials\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t28\n\x10\x46\x65tchCredentials\x12$\n\x0c\x46\x65tchRequest\x12\x06.Input\x1a\x0c.Credentialsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'init_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INPUT']._serialized_start=14
  _globals['_INPUT']._serialized_end=36
  _globals['_CREDENTIALS']._serialized_start=38
  _globals['_CREDENTIALS']._serialized_end=83
  _globals['_FETCHCREDENTIALS']._serialized_start=85
  _globals['_FETCHCREDENTIALS']._serialized_end=141
# @@protoc_insertion_point(module_scope)
